import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik, Oi } from "next/font/google";
import { ThemeProvider } from "../context/ThemeContext";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const oi = Oi({
  weight: "400",
  variable: "--font-oi",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rubik.variable} ${geistSans.variable} ${geistMono.variable} ${oi.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
